package com.bwie.android.work0214.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bwie.android.work0214.bean.ListBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LIST_BEAN".
*/
public class ListBeanDao extends AbstractDao<ListBean, Long> {

    public static final String TABLENAME = "LIST_BEAN";

    /**
     * Properties of entity ListBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CommodityId = new Property(0, Long.class, "commodityId", true, "_id");
        public final static Property CommodityName = new Property(1, String.class, "commodityName", false, "COMMODITY_NAME");
        public final static Property MasterPic = new Property(2, String.class, "masterPic", false, "MASTER_PIC");
        public final static Property Price = new Property(3, String.class, "price", false, "PRICE");
        public final static Property SaleNum = new Property(4, String.class, "saleNum", false, "SALE_NUM");
    }


    public ListBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ListBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LIST_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: commodityId
                "\"COMMODITY_NAME\" TEXT," + // 1: commodityName
                "\"MASTER_PIC\" TEXT," + // 2: masterPic
                "\"PRICE\" TEXT," + // 3: price
                "\"SALE_NUM\" TEXT);"); // 4: saleNum
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LIST_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ListBean entity) {
        stmt.clearBindings();
 
        Long commodityId = entity.getCommodityId();
        if (commodityId != null) {
            stmt.bindLong(1, commodityId);
        }
 
        String commodityName = entity.getCommodityName();
        if (commodityName != null) {
            stmt.bindString(2, commodityName);
        }
 
        String masterPic = entity.getMasterPic();
        if (masterPic != null) {
            stmt.bindString(3, masterPic);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(4, price);
        }
 
        String saleNum = entity.getSaleNum();
        if (saleNum != null) {
            stmt.bindString(5, saleNum);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ListBean entity) {
        stmt.clearBindings();
 
        Long commodityId = entity.getCommodityId();
        if (commodityId != null) {
            stmt.bindLong(1, commodityId);
        }
 
        String commodityName = entity.getCommodityName();
        if (commodityName != null) {
            stmt.bindString(2, commodityName);
        }
 
        String masterPic = entity.getMasterPic();
        if (masterPic != null) {
            stmt.bindString(3, masterPic);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(4, price);
        }
 
        String saleNum = entity.getSaleNum();
        if (saleNum != null) {
            stmt.bindString(5, saleNum);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ListBean readEntity(Cursor cursor, int offset) {
        ListBean entity = new ListBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // commodityId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // commodityName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // masterPic
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // price
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // saleNum
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ListBean entity, int offset) {
        entity.setCommodityId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCommodityName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMasterPic(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPrice(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSaleNum(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ListBean entity, long rowId) {
        entity.setCommodityId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ListBean entity) {
        if(entity != null) {
            return entity.getCommodityId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ListBean entity) {
        return entity.getCommodityId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
